version: "3.9"

services:
  ui:
    image: node:18.18.2-alpine3.18
    volumes:
      - ../frontend/:/app/
    ports:
      - "${FRONTEND_PORT-3000}:3000"

  backend:
    build:
      context: ../backend
      dockerfile: backend.Dockerfile
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-48997}/status"]
        interval: 10s
        timeout: 2s
        retries: 5
    volumes:
      - ../backend/app:/app/
      - ../backend/plugins:/app/app/plugins
    depends_on:
      - db
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "${BACKEND_PORT-48997}:80"

  casdoor:
    image: casbin/casdoor:latest
    restart: on-failure
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 45910:45910
    volumes:
      - ./_casdoor/conf:/conf
      - ./_casdoor/init_data.json:/init_data.json

  redis:
    image: ${REDIS_IMAGE-redis:alpine3.18}
    ports:
      - "${REDIS_PORT-63379}:6379"

  db:
    image: "${POSTGRES_IMAGE-postgres:15.4}"
    ports:
      - "${POSTGRES_PORT-55432}:5432"

  janus:
    build:
      context: ./_janus
      dockerfile: janusgraph.Dockerfile
    restart: on-failure
    ports:
      - "8182:8182"
    volumes:
      - "./_janus/janusgraph-dynamic.properties:/opt/janusgraph/janusgraph-dynamic.properties"
      - "./_janus/janusgraph-server.yaml:/etc/opt/janusgraph/janusgraph-server.yaml"
      - "./_janus/empty-sample.groovy:/opt/janusgraph/scripts/empty-sample.groovy"

  sdb:
    image: ${SCYLLA_IMAGE-scylladb/scylla:5.1}
    ports:
      - "${SDB_REST_PORT-10000}:10000"
      - "${CQL_PORT-9042}:9042"
      - "${THRIFT_PORT-9160}:9160"
      - "${INTERNODE_PORT-7000}:7000"
      - "${INTERNODE_ONE_PORT-7001}:7001"
      - "${JMX_PORT-7199}:7199"

  index:
    image: "${SOLR_IMAGE-solr:9.3.0-slim}"
    ports:
      - "${SOLR_PORT-8983}:8983"

  s3: # TODO: Add option to use ob/_seaweedfs/* eventually
    image: "${S3_IMAGE-minio/minio:RELEASE.2023-10-16T04-13-43Z}"
    ports:
      - 9000:9000
      - 9001:9001
